# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longname', models.CharField(max_length=100)),
                ('goodsimg', models.CharField(max_length=255)),
                ('brandname', models.CharField(max_length=100)),
                ('typename', models.CharField(max_length=100)),
                ('brandid', models.IntegerField()),
                ('typeid', models.IntegerField()),
                ('price', models.FloatField()),
                ('marketprice', models.FloatField()),
                ('detailid', models.IntegerField()),
            ],
            options={
                'db_table': 'zwyz_goods',
            },
        ),
    ]
