# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brandid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='detailid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='typeid',
            field=models.CharField(max_length=10),
        ),
    ]
