# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190315_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='fullgift',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='fullminus',
            field=models.CharField(default='', max_length=100),
        ),
    ]
