# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_goods_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fullminus',
            field=models.CharField(default='', max_length=200),
        ),
    ]
